### ISSUE TITLE
It dosen't work?

### ISSUE THREAD

**Issue by jayycobo** [zoony1337/TikTok-Shares-Botter#16]
did tiktok patch this

**Comment by Simpba** [comment]
There is a fix in Pull requests.

**Comment by jayycobo** [comment]
ok will download thanks

**Comment by jayycobo** [comment]
i am dumb how do i dowload this fix or do i have to go in the file itself

**Comment by yassine128** [comment]
> i am dumb how do i dowload this fix or do i have to go in the file itself

you download it like you would download any github repository.

**Comment by jayycobo** [comment]
im 

> > i am dumb how do i dowload this fix or do i have to go in the file itself
> 
> you download it like you would download any github repository.

im very dumb lmao can u help me discord: jayycobo #1069

**Comment by yassine128** [comment]
> im
> 
> > > i am dumb how do i dowload this fix or do i have to go in the file itself
> > 
> > 
> > you download it like you would download any github repository.
> 
> im very dumb lmao can u help me discord: jayycobo #1069

Just download it from here: https://github.com/LupusLeaks/TikTok-Shares-Botter

**Comment by jayycobo** [comment]
> er

thank you sir
